# Generated by Django 3.0.7 on 2020-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
                ('user_startdate', models.DateField(max_length=240)),
                ('user_end_date', models.DateField(max_length=250)),
                ('user_tz', models.CharField(max_length=250)),
            ],
        ),
    ]
